### ISSUE TITLE
Cant control AC

### ISSUE THREAD

**Issue by deltaclock** [fredrike/pytfiac#7]
Hello!

Im trying to use your lib to control my newly bought AC but it throws a connection timeout exception.

Steps I follow are:
1. Connect to the open wifi of my AC ( Air condition-faxxx)
2. Create a new instance of you class with ip 192.168.10.1, the router of the AC
3. asyncio.run(client.set_state(...))

I suspect this is a network issue for some reason but i have scanned the AC network and the only devices in it are the gateway and myself. I have done full udp scan on the router and only found 67 and 80 open.

Not sure how the phone and it are supposed to talk, the AC doesnt even show up in the TFIAC up after multiple tries. Not sure if its already paired but the app display is broken or what. I have even tried reversing their app and i definitely see some interesting stuff there like many broadcast messages but the data are encoded.

Do you have any clues on whats going or maybe how its the initial setup done?

Thanks

**Comment by fredrike** [comment]
Hi!

I heard something that Tfiac might not be working anymore. I suggest that you make sure that the phone app is working first.

**Comment by deltaclock** [comment]
I have tried many different things and the one that managed to pair my AC was [this](https://play.google.com/store/apps/details?id=com.ab.smartDevice&hl=en) one.

My AC has now closed its own wifi and connected as a client to my own wifi. Did a quick scan and udp/7777 is not open.
Probably in the near future i might reverse the protocol and make another py lib like yours for HASS integration :)

**Comment by fredrike** [comment]
There is discussions of the same app in the HA forums. I've got a tcp dump with traffic but have not had time to investigate further.

**Comment by deltaclock** [comment]
Cant seem to find the relevant threads from a quick search, would be helpful if you could link them.
Also im interested in the pcap (**tcp**dump?) to take a look.

**Comment by fredrike** [comment]
This is the thread, https://community.home-assistant.io/t/solved-for-local-access-a-c-app-named-tfiac-anyone-ever-heard-of-it/58169/36?u=fredrike

Do note that I've just built the Tfiac integration i don't have a compatable unit so I don't know much of what's going on here.
